# Generated by Django 3.1.4 on 2022-04-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cantidadequipos_cantidadpartidas_cantidadpersonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas',
            name='tasa_dolar',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='depreciacion',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
