# Generated by Django 3.1.4 on 2022-04-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220413_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materiales',
            old_name='depreciacion',
            new_name='desperdicio',
        ),
    ]
