# Generated by Django 3.1.4 on 2022-04-20 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220418_2334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partidas',
            name='equipos',
            field=models.ManyToManyField(blank=True, to='app.Equipos'),
        ),
        migrations.AlterField(
            model_name='partidas',
            name='materiales',
            field=models.ManyToManyField(blank=True, to='app.Materiales'),
        ),
        migrations.AlterField(
            model_name='partidas',
            name='personal',
            field=models.ManyToManyField(blank=True, to='app.Personal'),
        ),
    ]
