# Generated by Django 3.1.4 on 2022-04-23 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220420_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioMateriales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areas')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.materiales')),
            ],
            options={
                'verbose_name': 'PrecioMateriales',
                'verbose_name_plural': 'PrecioMateriales',
            },
        ),
    ]
