# Generated by Django 3.1.4 on 2022-04-24 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_precioequipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecioPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField(default=0)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.areas')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.personal')),
            ],
            options={
                'verbose_name': 'PrecioPersonal',
                'verbose_name_plural': 'PrecioPersonal',
            },
        ),
    ]
