# Generated by Django 3.1.4 on 2022-04-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_preciopersonal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cantidadequipos',
            name='cantidad',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='cantidadmateriales',
            name='cantidad',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='cantidadpartidas',
            name='cantidad',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='cantidadpersonal',
            name='cantidad',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='precioequipos',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='preciomateriales',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='preciopersonal',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
