# Generated by Django 3.1.4 on 2022-04-30 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220428_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='obras',
            old_name='tarifa_transforte',
            new_name='tarifa_transporte',
        ),
    ]
