# Generated by Django 3.1.4 on 2022-04-30 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20220430_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obras',
            name='partidas',
            field=models.ManyToManyField(blank=True, to='app.Partidas'),
        ),
    ]
