# Generated by Django 3.1.4 on 2022-05-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220430_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='materiales',
            name='precio',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='personal',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
