# Generated by Django 3.1.4 on 2022-05-03 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220503_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='materiales',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='personal',
            name='precio',
        ),
    ]
