# Generated by Django 3.1.4 on 2022-05-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20220503_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='materiales',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
