# Generated by Django 3.1.4 on 2022-05-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_equipos_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
