# Generated by Django 3.1.4 on 2022-05-07 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_personal_precio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='areas',
            options={'permissions': (('can_add_areas', 'Agregar áreas'), ('can_remove_areas', 'Eliminar áreas'), ('can_edit_areas', 'Modificar áreas')), 'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
    ]
