# Generated by Django 3.1.4 on 2022-05-08 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20220507_2136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partidas',
            options={'permissions': (('view_analisis', 'Ver análisis de precio unitario'), ('change_analisis', 'Modificar análisis de precio unitario')), 'verbose_name': 'Partida', 'verbose_name_plural': 'Partidas'},
        ),
    ]
