# Generated by Django 3.1.4 on 2022-05-15 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20220508_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='obras',
            options={'permissions': (('view_presupuesto', 'Ver presupuestos'), ('change_presupuesto', 'Modificar presupuestos'), ('report_presupuesto', 'Ver reportes de presupuestos'), ('report_presupuesto_pdf', 'Ver reportes de presupuestos en pdf'), ('report_presupuesto_excel', 'Ver reportes de presupuestos en excel')), 'verbose_name': 'Obra', 'verbose_name_plural': 'Obras'},
        ),
    ]
